const StaffOrder = require("../model/staffOrderModel")
const Table = require("../model/Table")
const mongoose = require("mongoose")

// Create a guest order from mobile app with automatic table status update
const createMobileGuestOrder = async (req, res) => {
  console.log("=" .repeat(80))
  console.log("📱📱📱 MOBILE APP ENDPOINT CALLED 📱📱📱")
  console.log("=" .repeat(80))
  
  try {
    const {
      orderId,
      customerName,
      customerMobile,
      branchId,
      branchName,
      categoryId,
      categoryName,
      tableId,
      tableNumber,
      peopleCount,
      items,
      subtotal,
      tax,
      serviceCharge,
      totalAmount,
      grandTotal,
      paymentMethod,
      paymentStatus,
      status,
      orderTime,
      notes,
    } = req.body

    console.log("📱 Mobile app - Received guest order creation request:", {
      orderId,
      tableId,
      tableNumber,
      branchId,
      categoryId,
      customerName,
      customerMobile,
      itemsCount: items?.length
    })
    
    console.log("📱 Mobile app - Full request body:", JSON.stringify(req.body, null, 2))

    // Validate required fields for guest orders
    if (!customerName || !customerName.trim()) {
      return res.status(400).json({
        success: false,
        message: "Customer name is required",
      })
    }

    if (!customerMobile || !customerMobile.trim()) {
      return res.status(400).json({
        success: false,
        message: "Customer mobile is required",
      })
    }

    // Validate mobile number format
    if (!/^[0-9]{10}$/.test(customerMobile.trim())) {
      return res.status(400).json({
        success: false,
        message: "Mobile number must be 10 digits",
      })
    }

    if (!branchId || !branchName) {
      return res.status(400).json({
        success: false,
        message: "Branch information is required",
      })
    }

    if (!tableNumber) {
      return res.status(400).json({
        success: false,
        message: "Table number is required",
      })
    }

    if (!items || !Array.isArray(items) || items.length === 0) {
      return res.status(400).json({
        success: false,
        message: "Order must contain at least one item",
      })
    }

    // Check if order already exists (only if orderId is provided)
    if (orderId) {
      const existingOrder = await StaffOrder.findOne({ orderId })
      if (existingOrder) {
        return res.status(200).json({
          success: true,
          message: "Order already exists",
          order: existingOrder,
        })
      }
    }

    let finalTableId = tableId || new mongoose.Types.ObjectId()

    // Update table status to reserved if tableId is provided
    if (tableId) {
      try {
        console.log(`📱 Mobile app - Updating table ${tableNumber} (ID: ${tableId}) to reserved`)
        
        const updatedTable = await Table.findByIdAndUpdate(
          tableId,
          { status: "reserved" },
          { new: true }
        )

        if (updatedTable) {
          console.log(`✅ Mobile app - Table ${tableNumber} status updated to reserved successfully`)
        } else {
          console.log(`⚠️ Mobile app - Table ${tableNumber} not found, but continuing with order creation`)
        }
      } catch (tableError) {
        console.error(`❌ Mobile app - Error updating table status:`, tableError)
        // Continue with order creation even if table update fails
      }
    } else {
      console.log(`⚠️ Mobile app - No tableId provided, skipping table status update`)
    }

    // Create the guest order using StaffOrder model
    // Note: orderId will be auto-generated by the model's pre-save hook if not provided
    const orderData = {
      customerName: customerName.trim(),
      customerMobile: customerMobile.trim(),
      branchId: branchId,
      branchName,
      categoryId: categoryId,
      categoryName: categoryName,
      tableId: finalTableId,
      tableNumber,
      peopleCount: Number.parseInt(peopleCount) || 1,
      items,
      subtotal: Number.parseFloat(subtotal) || 0,
      tax: Number.parseFloat(tax) || 0,
      serviceCharge: Number.parseFloat(serviceCharge) || 0,
      totalAmount: Number.parseFloat(totalAmount) || 0,
      grandTotal: Number.parseFloat(grandTotal) || 0,
      paymentMethod: paymentMethod || "cash",
      paymentStatus: paymentStatus || "pending",
      orderTime: new Date(orderTime) || new Date(),
      notes: notes || `Mobile app guest order from Table ${tableNumber}`,
      status: status || "pending",
      isGuestOrder: true,
      // Set a temporary orderId - the pre-save hook will replace it with proper format
      orderId: `TEMP-${Date.now()}`
    }

    // Only override orderId if provided and not "N/A"
    if (orderId && orderId !== "N/A") {
      orderData.orderId = orderId
    }

    console.log("📱 Mobile app - Creating order with data:", JSON.stringify(orderData, null, 2))

    const guestOrder = new StaffOrder(orderData)
    
    console.log("📱 Mobile app - Order instance created, attempting to save...")

    await guestOrder.save()

    console.log("✅ Mobile app - Guest order created successfully:", guestOrder.orderId)

    res.status(201).json({
      success: true,
      message: "Mobile guest order created successfully and table status updated to reserved",
      order: guestOrder,
      tableStatusUpdated: !!tableId,
    })
  } catch (error) {
    console.error("❌ Mobile app - Error creating guest order:", error)
    console.error("❌ Error stack:", error.stack)
    console.error("❌ Error details:", {
      name: error.name,
      message: error.message,
      code: error.code
    })
    
    // Provide more specific error messages
    let errorMessage = "Error creating mobile guest order"
    if (error.code === 11000) {
      errorMessage = "Duplicate order detected. This order may already exist."
    } else if (error.name === "ValidationError") {
      errorMessage = `Validation error: ${error.message}`
    }
    
    res.status(500).json({
      success: false,
      message: errorMessage,
      error: error.message,
      details: error.errors ? Object.keys(error.errors).map(key => ({
        field: key,
        message: error.errors[key].message
      })) : undefined
    })
  }
}

module.exports = {
  createMobileGuestOrder,
}

// Update existing order with additional items - Creates NEW KOT for additional items but keeps same order
const updateMobileGuestOrderItems = async (req, res) => {
  console.log("=" .repeat(80))
  console.log("📱📱📱 MOBILE APP - ADD MORE ITEMS (NEW KOT, SAME ORDER) 📱📱📱")
  console.log("=" .repeat(80))
  
  try {
    const { id } = req.params
    const {
      additionalItems,
      additionalSubtotal,
      additionalTax,
      additionalServiceCharge,
      additionalGrandTotal,
    } = req.body

    console.log("📱 Mobile app - Order ID:", id)
    console.log("📱 Mobile app - Additional items:", additionalItems)

    // Validate required fields
    if (!additionalItems || !Array.isArray(additionalItems) || additionalItems.length === 0) {
      return res.status(400).json({
        success: false,
        message: "Additional items are required",
      })
    }

    // Find the existing order
    const existingOrder = await StaffOrder.findById(id)
    
    if (!existingOrder) {
      return res.status(404).json({
        success: false,
        message: "Order not found",
      })
    }

    console.log("📱 Mobile app - Current order:", existingOrder.orderId)
    console.log("📱 Mobile app - Current items count:", existingOrder.items.length)

    // Generate a NEW KOT number for the additional items
    // Check ALL orders to find the highest KOT number today
    const today = new Date()
    const todayStart = new Date(today.setHours(0, 0, 0, 0))
    const todayEnd = new Date(today.setHours(23, 59, 59, 999))

    // Find ALL orders with items that have KOT numbers today
    const ordersWithKots = await StaffOrder.find({
      branchId: existingOrder.branchId,
      createdAt: { $gte: todayStart, $lte: todayEnd }
    }).sort({ createdAt: -1 })

    let highestKotNumber = 0
    
    // Check all orders and their items for KOT numbers
    ordersWithKots.forEach(order => {
      // Check order-level KOT
      if (order.kotNumber) {
        const match = order.kotNumber.match(/KOT-(\d+)/)
        if (match) {
          const num = parseInt(match[1])
          if (num > highestKotNumber) {
            highestKotNumber = num
          }
        }
      }
      
      // Check item-level KOTs
      if (order.items && order.items.length > 0) {
        order.items.forEach(item => {
          if (item.kotNumber) {
            const match = item.kotNumber.match(/KOT-(\d+)/)
            if (match) {
              const num = parseInt(match[1])
              if (num > highestKotNumber) {
                highestKotNumber = num
              }
            }
          }
        })
      }
    })

    const newKotNumber = `KOT-${(highestKotNumber + 1).toString().padStart(3, '0')}`
    console.log("📱 Mobile app - Highest KOT found:", highestKotNumber)
    console.log("📱 Mobile app - Generated new KOT:", newKotNumber)

    // Add KOT number to each additional item
    const itemsWithKot = additionalItems.map(item => ({
      ...item,
      kotNumber: newKotNumber
    }))

    console.log("📱 Mobile app - Items with new KOT:", itemsWithKot.map(i => ({ name: i.name, kot: i.kotNumber })))

    // Merge items - add new items with KOT number to existing items
    const updatedItems = [...existingOrder.items, ...itemsWithKot]
    
    console.log("📱 Mobile app - All items after merge:")
    updatedItems.forEach((item, idx) => {
      console.log(`  ${idx + 1}. ${item.name} - KOT: ${item.kotNumber || 'NO KOT'}`)
    })
    
    // Calculate new totals
    const updatedSubtotal = (existingOrder.subtotal || existingOrder.totalAmount) + (additionalSubtotal || 0)
    const updatedTax = (existingOrder.tax || 0) + (additionalTax || 0)
    const updatedServiceCharge = (existingOrder.serviceCharge || 0) + (additionalServiceCharge || 0)
    const updatedGrandTotal = (existingOrder.grandTotal || existingOrder.totalAmount) + (additionalGrandTotal || 0)

    // Update the order with new items and totals
    existingOrder.items = updatedItems
    existingOrder.markModified('items') // Mark items array as modified for Mongoose
    existingOrder.subtotal = updatedSubtotal
    existingOrder.totalAmount = updatedSubtotal
    existingOrder.tax = updatedTax
    existingOrder.serviceCharge = updatedServiceCharge
    existingOrder.grandTotal = updatedGrandTotal
    existingOrder.notes = `${existingOrder.notes || ''} | Additional items added with ${newKotNumber}`

    await existingOrder.save()

    console.log("✅ Mobile app - Order updated with new KOT")
    console.log("📱 Mobile app - Same Order ID:", existingOrder.orderId)
    console.log("📱 Mobile app - New KOT:", newKotNumber)
    console.log("📱 Mobile app - Total items:", updatedItems.length)

    res.status(200).json({
      success: true,
      message: "Additional items added with new KOT number",
      order: existingOrder,
      newKotNumber: newKotNumber,
    })
  } catch (error) {
    console.error("❌ Mobile app - Error adding items:", error)
    res.status(500).json({
      success: false,
      message: "Error adding items",
      error: error.message,
    })
  }
}

module.exports = {
  createMobileGuestOrder,
  updateMobileGuestOrderItems,
}
